site_name: Heurist ETL

theme:
  name: readthedocs

plugins:
  - search
  - gen-files:
      scripts:
      - scripts/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  # - mkdocs-autoapi:
  #     autoapi_keep_files: True
  #     autoapi_dir: heurist
  #     autoapi_add_nav_entry: Reference
  - mkdocstrings:
      handlers:
        python:
          paths: ["./heurist"]
          options:
            docstring_options:
              ignore_init_summary: false
            docstring_section_style: list
            filters: ["!^_"]
            heading_level: 1
            inherited_members: true
            merge_init_into_class: true
            parameter_headings: true
            separate_signature: true
            show_root_heading: true
            show_root_full_path: false
            show_signature_annotations: true
            show_source: false
            show_symbol_type_heading: false
            show_symbol_type_toc: false
            signature_crossrefs: true
            summary: true

markdown_extensions:
  - pymdownx.highlight
  - toc:
      permalink: "#"

nav:
- Home: index.md
  # - Overview: index.md
  # - Credits: credits.md
  # - License: license.md
- Usage:
  - usage/index.md
  - Guides:
    - Recipes: usage/recipes.md
    - Troubleshooting: usage/troubleshooting.md
# defer to gen-files + literate-nav
- Code Reference: reference/
- Development:
  - Contributing: development/contributing.md
  - Code of Conduct: development/code_of_conduct.md
  - Coverage: development/coverage.md
  - Publishing: development/publishing.md