name: badges

on:
  push:
    paths:
      - "tests/**"
      - ".github/workflows/badge-update.yml"
    branches:
      - main
  workflow_call:

jobs:
  build:
    name: badges
    runs-on: ubuntu-latest
    env:
      HEURIST_USER: ${{ secrets.HEURISTUSER }}
      HEURIST_PASS: ${{ secrets.HEURISTPASS }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install .
          pip install pytest
          pip install coverage
          pip install genbadge[all]
      - name: Coverage badge
        run: |
            export DB_LOGIN=$HEURIST_USER
            export DB_PASSWORD=$HEURIST_PASS
            export DB_NAME=jbcamps_gestes
            coverage run -m pytest
            coverage xml
            genbadge coverage -i coverage.xml
            mv coverage-badge.svg docs/assets
      - name: Tests badge
        run: |
            python -m pytest --junitxml=reports/junit/junit.xml
            genbadge tests
            mv tests-badge.svg ./docs/assets
      - name: Commit data
        run: |
            if git diff docs/assets | grep . > /dev/null ; then
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git pull
            git add docs/assets/*.svg
            git commit -m "update badges"
            git push
            fi